//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class albums
    {
        public int albums_id { get; set; }
        public string albums_name { get; set; }
        public Nullable<int> styles_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> song_id { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public string file_path { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual songs songs { get; set; }
        public virtual styles styles { get; set; }
    }
}
