//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class artists
    {
        public artists()
        {
            this.groups = new HashSet<groups>();
        }
    
        public int artist_id { get; set; }
        public string artist_name { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
    }
}
