//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.albums = new HashSet<albums>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public Nullable<int> artist_id { get; set; }
    
        public virtual ICollection<albums> albums { get; set; }
        public virtual artists artists { get; set; }
    }
}
