//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZMYA2Entities : DbContext
    {
        public ZMYA2Entities()
            : base("name=ZMYA2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<albums> albums { get; set; }
        public DbSet<artists> artists { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<songs> songs { get; set; }
        public DbSet<styles> styles { get; set; }
    }
}
